import {
  CodeIcon,
  FileIcon,
  ImageIcon,
  TableIcon,
  TextIcon,
  VideoIcon,
  Heading1Icon,
  Heading2Icon,
  Heading3Icon,
  ListIcon,
  LinkIcon,
  QuoteIcon,
  PanelLeftCloseIcon,
  SlashIcon,
  ListCollapseIcon,
  ListOrderedIcon,
  PanelLeftIcon,
  GridIcon,
  LucideTableColumnsSplit,
} from 'lucide-react';

export const COMMAND_MENU_DEFAULT_ICONS_MAP: Record<string, any> = {
  Paragraph: TextIcon,
  HeadingOne: Heading1Icon,
  HeadingTwo: Heading2Icon,
  HeadingThree: Heading3Icon,
  Code: CodeIcon,
  Embed: LinkIcon,
  Image: ImageIcon,
  Video: VideoIcon,
  Blockquote: QuoteIcon,
  TodoList: ListIcon,
  BulletedList: ListIcon,
  NumberedList: ListIcon,
  Table: TableIcon,
  Callout: PanelLeftCloseIcon,
  File: FileIcon,
  Divider: SlashIcon,
  Accordion: ListCollapseIcon,
  Steps: ListOrderedIcon,
  Tabs: PanelLeftIcon,
  CodeGroup: CodeIcon,
  Carousel: GridIcon,
  TableOfContents: LucideTableColumnsSplit
};
