name: 💡 General Feature Request
description: Have a new idea/feature? Let us know...
title: "[FEATURE] <description>"
labels: ["⭐ goal: addition", "🚦 status: awaiting triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature report! You can also join our Discord community [here](https://discord.gg/Dt8rhSTjsn) 🦄
  - type: checkboxes
    id: duplicates
    attributes:
      label: Is this a unique feature?
      description: Increase the chances of your issue being accepted by making sure it has not been raised before.
      options:
        - label: I have checked "open" AND "closed" issues and this is not a duplicate
          required: true
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: dropdown
    id: assignee
    attributes:
      label: Do you want to work on this issue?
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: false
